### ISSUE TITLE
[doc] Figure&nbsp;8.5:  Stratos UI Cloud Foundry Console 

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-cap#1027] opened 2020-11-13 14:16 UTC
Figure&nbsp;8.5:  Stratos UI Cloud Foundry Console :

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#id-1.3.4.8.5.18

Same issue, new screenshot. I believe this is the wrong screenshot, it's just the console

**Comment by KucharczykL** [comment] 2020-11-24 11:06
Duplicate of #1026 because it's the same entity.

**Closed by KucharczykL** 2020-11-24 11:06 UTC
Labels: bug, low priority
