### ISSUE TITLE
[doc] 4.1  Deploying NGINX Ingress Controller

### ISSUE THREAD

**Issue by alexrenna** [SUSE/doc-cap#708] opened 2020-02-09 09:37 UTC
4.1  Deploying NGINX Ingress Controller

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-deploy-ingress-controller

### when installing nginx ingress controller, following the documented steps, I get the following error:

helm install suse/nginx-ingress --name nginx-ingress --namespace ingress --set rbac.create=true
Error: release nginx-ingress failed: namespaces "ingress" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "ingress"

to fix the error I did the following:
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'

**Comment by zoopster** [comment] 2020-02-13 21:10
Not sure you would need to do this if you had setup helm correctly prior to the helm install? Maybe there needs to be a reference to a proper helm setup before this (if not there already?)

**Comment by btat** [comment] 2020-09-15 23:47
Closing as the structure and ordering of the Deployment Guide was overhauled with the 2.0 release and should no longer lead to confusion caused by hopping between chapters/sections for the required steps.

For 1.x, the proper Helm setup already exists, though not directly within the Ingress chapter/section itself.

Step 1 of https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-deploy-ingress-controller instructs the user to prep their cluster based on their platform (with the links to each of AKS, CaaSP, EKS, GKE accordingly) and stop when they reach the UAA deployment step. In the chapters for each platform, there is a section for the Helm/Tiller setup prior to the UAA deployment step.

**Closed by btat** 2020-09-15 23:47 UTC
