### ISSUE TITLE
[doc] Figure&nbsp;1.1:  Minimal Example Production Deployment 

### ISSUE THREAD

**Issue by alexrenna** [SUSE/doc-cap#707] opened 2020-02-08 08:48 UTC
Figure&nbsp;1.1:  Minimal Example Production Deployment 

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#fig-cap-min-prod-arch

the picture still shows Velum Dashboard, that is not present anymore on current CaaSP version 4

**Comment by btat** [comment] 2020-02-10 17:23
Closing as duplicate of #637

**Closed by btat** 2020-02-10 17:23 UTC
Labels: duplicate
