### ISSUE TITLE
az aks create --nodepool-name option not working

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#324] opened 2019-02-06 13:55 UTC
7.2  Create Resource Group and AKS Instance

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.create-aks-instance

The command az aks create --resource-group $RGNAME --name $AKSNAME \
 --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
 --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE \
 --node-osdisk-size=60 --nodepool-name $NODEPOOLNAME

Does not work anymore. For me it worked by removing --nodepool-name $NODEPOOLNAME
So the new command is az aks create --resource-group $RGNAME --name $AKSNAME \
 --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
 --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE \
 --node-osdisk-size=60

**Comment by it-slav** [comment] 2019-02-06 15:54
Yes I did
I have scripts that do all that, and last week it worked. Today the did not so I think azure has changed something in their end.

**Comment by btat** [comment] 2019-02-07 23:39
@it-slav what version of the `az` cli was used when it worked and when it didn't? Our team mentioned the option is only supported in recent version of the cli and omitting the option leads to issues down the line

**Comment by satadruroy** [comment] 2019-02-08 00:45
I had `azure-cli` version 2.50 and it supports `--nodepool-option` - upgraded to the latest 2.57 and it still supports the flag as documented at: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

If you omit the `--nodepool-name` flag then the following commands for setting swap accounting will need to be adjusted because the command to list the worker node VM names makes use of the value of that flag. You can also find the names of the worker node VMs by looking into the resource group hosting the cluster VMs (starts with `MC`) and then execute the rest of the commands.

**Comment by cjschroder** [comment] 2019-02-14 20:13
closing; this needs to be verified by engineering if there is a change

**Comment by troytop** [comment] 2019-02-21 18:57
As with #333 this may still end up being a docs issue. Leave open as blocked pending verification from QA or engineering.

**Comment by satadruroy** [comment] 2019-02-21 22:08
`--nodepool-name` is still supported. Please make sure you don't have `az` cli AKS preview extensions installed as described here.

https://github.com/Azure/azure-cli/issues/8572

**Comment by HartS** [comment] 2019-02-21 23:47
@it-slav what `az` cli version are you using? And when you say it `does not work anymore`? Can you share the error message you get when you run it?

**Comment by btat** [comment] 2019-03-13 17:27
@it-slav is this still an issue for you? If so, could you please provide the information requested above so our team can look into it. Also, as @satadruroy mentioned, please ensure you don't have the preview extensions installed.

**Comment by it-slav** [comment] 2019-03-18 12:40
Yes, still an issue.
_version_
peter2@linux-jo56:~/cap/azure_cap_scripts-20190318> az -v
azure-cli                         2.0.60
Following the instructions at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest 

_Still an issue_
peter2@linux-jo56:~/cap/azure_cap_scripts-20190318> echo $NODEPOOLNAME
PApool2
peter2@linux-jo56:~/cap/azure_cap_scripts-20190318> az aks create --resource-group $RGNAME --name $AKSNAME \
>  --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
>  --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE \
>  --node-osdisk-size=60 --nodepool-name $NODEPOOLNAME \
>  --kubernetes-version 1.11.8
Operation failed with status: 'Bad Request'. Details: The value of parameter agentPoolProfile.name is invalid.

_this works_
peter2@linux-jo56:~/cap/azure_cap_scripts-20190318> az aks create --resource-group $RGNAME --name $AKSNAME  --node-count $NODECOUNT --admin-username $ADMINUSERNAME  --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE  --node-osdisk-size=60 --kubernetes-version 1.11.8

**Comment by satadruroy** [comment] 2019-03-18 16:31
Hi Peter, repeating my previous comment - do you have AKS preview extensions installed as that would cause this issue as described here.

https://github.com/Azure/azure-cli/issues/8572

**Comment by it-slav** [comment] 2019-03-19 09:00
Ahh, missed that extension part. No I do not have AKS preview extensions installed. Is it documented as a pre-req?

**Comment by gaktive** [comment] 2019-03-20 18:19
Billy will create a bug to verify what we should do here with the nodepools in case we have to add labels somewhere and have QA look at this first. Still need clarification on the preview extensions bit.

**Comment by btat** [comment] 2019-03-21 18:50
Card created: https://trello.com/b/FtTYHGGU/platform-team-na-sprint-board

@it-slav could you please provide the full output of `az --version` for reference

**Comment by HartS** [comment] 2019-03-21 22:13
> Why do we use it --nodepool-name? I just removed it and it works fine (including remove it later down when enabling swap)

@it-slav it's not strictly required, setting `--nodepool-name` just affects the prefix of resources that get created in your aks cluster.

The default `--nodepool-name` value (if not set) is `nodepool1`, so, for example, the names of the VMs created as part of my AKS cluster would start with `aks-nodepool1` by default

**Comment by it-slav** [comment] 2019-03-22 06:23
peter@linux-jo56:~> az --version
azure-cli                         2.0.60

acr                                2.2.2
acs                               2.3.19
advisor                            2.0.0
ams                                0.4.2
appservice                        0.2.15
backup                             1.2.1
batch                              4.0.0
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.8
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.60
cosmosdb                           0.2.8
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.4
extension                          0.2.3
feedback                           2.1.4
find                               0.3.0
hdinsight                          0.3.2
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.12
kusto                              0.2.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.4
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.8
redis                              0.4.1
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.11
role                               2.4.2
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.14
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.16

Python location '/usr/lib64/az/bin/python'
Extensions directory '/home/peter/.azure/cliextensions'

Python (Linux) 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by btat** [comment] 2019-04-03 17:41
This https://trello.com/c/TbbPHf9L/992-error-when-using-nodepool-name-option-during-az-aks-create card was created to look into the issue

**Comment by bikramnehra** [comment] 2019-04-05 18:44
@it-slav I think I figured out what the issue is. It is basically the value of for `--nodepool-name` that you are providing. As per my tests, I have noticed that azure rejects any value having uppercase characters for this parameter. I have tried with `PApool2` and `Papool2` and saw same error message that you are seeing:

```
$ az aks create --resource-group $RGNAME --name $AKSNAME \
   --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
   --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE \
   --node-osdisk-size=60 --nodepool-name PApool2 --kubernetes-version 1.11.8
Operation failed with status: 'Bad Request'. Details: The value of parameter agentPoolProfile.name is invalid.
```

Though, following command worked fine for me:

```
$ az aks create --resource-group $RGNAME --name $AKSNAME \
   --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
   --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE \
   --node-osdisk-size=60 --nodepool-name papool2 --kubernetes-version 1.11.8
 - Running ..
```
Although, its not trivial just by looking at the azure cli [docs.](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)

**Comment by btat** [comment] 2019-04-05 19:02
Added note to not use uppercase characters in https://github.com/SUSE/doc-cap/commit/42af593c799a4b90024100f3377c5af3851d555c

**Closed by btat** 2019-04-05 19:02 UTC
Labels: blocked, bug
