### ISSUE TITLE
[doc] 5.1  Prerequisites - Install SUSE CaaS Platform -> needs to be updated to caasp v4

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#691] opened 2020-01-31 14:41 UTC
5.1  Prerequisites

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-prereqs-prod

---------------------
It seems that there is still a lot CaaSP v3.. I believe it would be better to just link this to the installation guide of CaaSP v4 instead of repeating the details, here.

**Comment by btat** [comment] 2020-01-31 17:41
Closing as duplicate of #575

**Closed by btat** 2020-01-31 17:41 UTC
