### ISSUE TITLE
[doc] 4.1  Deploying NGINX Ingress Controller

### ISSUE THREAD

**Issue by jmlambert78** [SUSE/doc-cap#622] opened 2019-11-22 07:25 UTC
4.1  Deploying NGINX Ingress Controller

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-deploy-ingress-controller
In this doc one speak of UAA deployment, while UAA is now deployed with SCF in a shot.
So this doc is not aligned with version 1.5

**Comment by KucharczykL** [comment] 2020-01-16 16:06
Isn't UAA deployed in one shot only when user explicitly makes it so by specifying during the deployment of SCF?

```
enable:
 uaa: true
```

**Comment by jmlambert78** [comment] 2020-01-16 16:36
I think that Rania indicated that if I do not deploy UAA separately IC is not usable for the moment.



 

De : Lukáš Kucharczyk <notifications@github.com> 
Envoyé : jeudi 16 janvier 2020 17:06
À : SUSE/doc-cap <doc-cap@noreply.github.com>
Cc : Jean Marc Lambert <jmlambert78@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [SUSE/doc-cap] [doc] 4.1 Deploying NGINX Ingress Controller (#622)

 

Isn't UAA deployed in one shot only when user explicitly makes it so by specifying during the deployment of SCF?

enable:
 uaa: true

**Comment by KucharczykL** [comment] 2020-02-05 16:10
Duplicate of #556.

**Closed by KucharczykL** 2020-02-05 16:10 UTC
